### ISSUE TITLE
Request: Add 'online' detection

### ISSUE THREAD

**Issue by gwnichol** [ZacheryThomas/srpy#4]
Hello again,
Would it make sense to add a property for whether a device is reporting as online? I'd like to be able to see that info in Home Assistant.

Partial `devices_resp.json()` for my one offline device:
```
{
    'attributes': [{'last_read_at': '2020-08-06T16:48:43Z', 'name': 'leak', 'state': 'false'}],
    'battery_level': 100,
    'battery_powered': True,
    'name': 'Kitchen Sink - Leak Sensor',
    'online': False,
    'warning': False
}
```

Unfortunately the `leak` attribute is reporting false and that's what is being displayed on Home Assistant. There's no indication from the device properties that anything is wrong.

Would it make sense to add an `_online: bool` to the `Device` base?

Thank you for making this and the Home Assistant integration!

**Comment by ZacheryThomas** [comment]
Hi!

Same deal as mentioned here: https://github.com/ZacheryThomas/smartrent.py/issues/3#issuecomment-1134673637

I think it does make sense to support detecting if a device is `online` or not though.

And yeah no problem! Its been a pet project of mine for the past couple of months and its cool to see people using it! Thanks for reaching out and giving feedback 👍

**Comment by ZacheryThomas** [comment]
Added this feature in the latest release!

https://github.com/ZacheryThomas/smartrent.py/releases/tag/v0.2.5
